### ISSUE TITLE
Change tags edition to look like the github's labels

### ISSUE THREAD

**Issue by juanbono** [lambdaclass/elephant_in_the_room#314]
![label](https://user-images.githubusercontent.com/2772065/42891022-b45c7d28-8a84-11e8-82ab-52dd616e3a33.png)

**Comment by hernanex3** [comment]
<img width="794" alt="screen shot 2018-07-19 at 3 00 44 pm" src="https://user-images.githubusercontent.com/8556088/42961217-8da7cf94-8b64-11e8-8bc9-c2423d485585.png">

**Comment by hernanex3** [comment]
#356
