### ISSUE TITLE
Fix popular section / update redis database

### ISSUE THREAD

**Issue by hernanex3** [lambdaclass/elephant_in_the_room#379]
Clean the redis database when doing a `make clean_init_db`. Currently we only clean the postgresql database. This can lead to an buggy or inconsistent popular view.

**Comment by hernanex3** [comment]
Also when we delete a post, we should remove it from redis.

**Comment by hernanex3** [comment]
We are noticing that after some time the popular section starts losing posts. For example after a fresh database reset it works fine but a day after it doesn't.

**Comment by hernanex3** [comment]
PR: #403

**Comment by unbalancedparentheses** [comment]
@AminArria create new issue explaning what happens and how to fix it and close this one
