### ISSUE TITLE
Fonts from post should be bigger and there should be more separation between lines and paragraphs

### ISSUE THREAD

**Issue by unbalancedparentheses** [lambdaclass/elephant_in_the_room#399]
Compare:
Now:
![screen shot 2018-07-24 at 11 14 11 pm](https://user-images.githubusercontent.com/569014/43175821-5a403f24-8f97-11e8-8606-199feab65720.png)

Objective:
![screen shot 2018-07-24 at 11 14 12 pm](https://user-images.githubusercontent.com/569014/43175820-5a1db12a-8f97-11e8-9324-3ae86c06705e.png)

**Comment by hernanex3** [comment]
PR:  #421
