### ISSUE TITLE
Show the date of posts when listing them

### ISSUE THREAD

**Issue by hernanex3** [lambdaclass/elephant_in_the_room#73]
Show:
- 'Just now' if it's less than 5 minutes.
- Show the minutes if higher than 5 minutes.
- After the 60 minutes, should show hours.
- After 24 hours should show days.
- After 14 days should show the plain date of the post.

**Comment by juanbono** [comment]
added in [this commit](https://github.com/lambdaclass/elephant_in_the_room/commit/1c3c50870cecf32c2c82ad6798f99d33546ff627)
