### ISSUE TITLE
Update npm dependencies

### ISSUE THREAD

**Issue by hernanex3** [lambdaclass/elephant_in_the_room#99]
<img width="556" alt="screen shot 2018-06-04 at 5 17 21 pm" src="https://user-images.githubusercontent.com/8556088/40939659-c439a684-681b-11e8-8419-60ca6e19bd37.png">

**Comment by hernanex3** [comment]
https://docs.npmjs.com/getting-started/running-a-security-audit

**Comment by juanbono** [comment]
I fixed 16 vulnerabilities in this [PR](https://github.com/lambdaclass/elephant_in_the_room/issues/99), the remaining vulnerabilities cannot be solved because they are brunch dependencies.

**Comment by juanbono** [comment]
Fixed!
